version: '3.8'

services:
  frontend:
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - microservices-network

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "3001:3001"
    networks:
      - microservices-network

  bank-service:
    build:
      context: ./bank-service
    ports:
      - "3002:3002"
    networks:
      - microservices-network

  stock-service:
    build:
      context: ./stock-service
    ports:
      - "3003:3003"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
